### PR TITLE
Give herokuish user sudo access

### PR DESCRIPTION
**Pull request by casperisfine**
THis gives the `herokuishuser` sudo access. 

The goal being to allow to install packages in a simpler way.

However we should probably remove that sudo access when finalizing the build.

cc @DazWorrall

### CODE REVIEW

**Comment by DazWorrall** [comment]
Removing it at the end of `buildpack-execute` looks to be a good place: https://github.com/Shopify/herokuish/blob/191b9a793cf75f072dced5c0caa78b842015fa4f/include/buildpack.bash#L119

Or we could grant sudo access around `buildpack-execute` in the wrapper, and maybe conditionally: https://github.com/Shopify/herokuish/blob/191b9a793cf75f072dced5c0caa78b842015fa4f/include/buildpack.bash#L29

**Comment by casperisfine** [comment]
I'm trying to use this PR to build Shopify, but it's not working because contrary to release version it's missing `/usr/bin/builder`

I checked what it look like n 
```bash
root@70112e4c000d:/# cat /usr/bin/builder 
#!/bin/bash
set -euo pipefail

export SSH_AUTH_SOCK=/tmp/ssh.sock
su - herokuishuser -c "ssh-agent -a /tmp/ssh.sock"
[ -f $HOME/.ssh/id_rsa ] && ssh-add $HOME/.ssh/id_rsa
export USER=herokuishuser

export RAILS_ENV="${ENV:-production}"
# this needs to be in-sync with pipa buildpack pipeline
export DATABASE_URL="mysql2://root@127.0.0.1:3306/buildonly"
export RACK_ENV="$RAILS_ENV"

echo "Starting build"
herokuish buildpack build
```

but I can't find this script anywhere :/

**Comment by DazWorrall** [comment]
Found it @casperisfine - there's another layer: https://github.com/Shopify/shopify-docker-images/tree/master/herokuish

**Comment by casperisfine** [comment]
Yup, closing in favor of https://github.com/Shopify/shopify-docker-images/pull/316

**Pull request closed without merging**
